-- Update: Kleinanzeigen 3282873847 (Bonn-Endenich, Carl-Justi-Str. 23, WE 039)
-- Nachbewertung 13.08.2026 mit Unterlagen (HGA 2024, WP 2025, Grundbuch, Energieausweis, Kurzexpose, ALKIS).
-- Match ueber data->>'link'; aktualisiert notizen, wunschpreis, ansprechpartner-Kontakt, updated_at (JSON + Spalte).

update public.search_properties
set
  data = jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(
    data,
    '{notizen}',
    to_jsonb('Analyse 13.08.2026 (Nachbewertung mit Unterlagen): Kaufen wenn Preis passt. Zielpreis 210.000-215.000 EUR (inkl. ~15-20 TEUR Renovierungs-Capex), Erstgebot ~205.000 EUR, Schmerzgrenze 220.000 EUR. App-Logik: CF +63 EUR/M schon bei 239.000 EUR (Faktor 20,3, Brutto 4,92 %). Konservativ mit ECHTEN Zahlen: n. uml. nur 47,84 EUR/M lt. WP 2025 (statt 50-120 geschaetzt) + eigene Instandhaltung 63 EUR = CF -48 EUR bei Inseratspreis, traegt ab ~226.500 EUR; mit Vonovia-eigener Mietkalkulation 957 EUR/M (Expose: 11.484 EUR p. a.) ab ~220.500 EUR.\nUnterlagen-Fazit: WEG deutlich besser als befuerchtet - Ruecklage 901.933 EUR per 31.12.2024 (Anteil WE 39: 8.897 EUR; UG1 Hs 19-23: 434.695 EUR = ~113 EUR/m2), Zufuehrung 71.300 EUR/a, Aufzugreparaturen aus Ruecklage bezahlt, HGA 2024 mit Guthaben 209,76 EUR, keine Sonderumlage-Anzeichen. Verwaltung extern: TERRENUM GmbH Bonn (keine Vonovia-Tochter). Grundbuch sauber: Volleigentum 62/10.000 MEA (Flur 7, Flurstuecke 1664/1665/1668, zus. ~2,2 ha), Abt. II + III komplett geloescht; ABER Veraeusserungsbeschraenkung Par. 12 WEG - Kauf von Vonovia ausgenommen (Erstveraeusserung), Wiederverkauf braucht Verwalterzustimmung. Eingetragene Eigentuemerin: Deutsche Annington Beteiligungsverwaltungs GmbH (Vonovia-Konzern) - Verkaeuferidentitaet im Kaufvertrag pruefen.\nRisiken bestaetigt/neu: Wohnung real UNRENOVIERT (echte Expose-Fotos: Bad/WC/Kueche Original 1974, Teppiche verschlissen/fleckig, Kuechenwand beschaedigt) = 15-20 TEUR Capex vor Vermietung, Inserats-Fotos waren digital beschoenigt; Waermeerzeuger Bj. 1999 (27 J., Tausch absehbar, Kessel-Art/GEG-30-Jahre-Frist klaeren - Ruecklage deckt das aber locker); WW elektrisch dezentral (Durchlauferhitzer = Eigen-Capex bei Defekt, hohe Mieter-Stromkosten druecken Kaltmietenspielraum); Huelle unsaniert (Ausweis-Empfehlungen: Dach, Fassade, Fenster, Kellerdecke pruefen/verbessern); ALKIS: Bahntrasse direkt westlich der Anlage (Laerm bei Besichtigung pruefen); Vonovia-Stimmenmehrheit strukturell bestaetigt (Hs 26-34 komplett ungeteilt bei Vonovia + unverkaufte WE Hs 19-24); Energieausweis gilt nur bis 01.09.2029.\nOffen: ETV-Protokolle 2023-2025 (im Paket NICHT enthalten!), Kessel-Art + geplante Sanierungen, Teilungserklaerung/Gemeinschaftsordnung, Vonovia-Restanteil in Zahlen, Sondernutzungsrechte-Zuordnung. Nachfass-Mail an Hrn. Duelz entworfen.\nKontakt: Elmar Duelz (Mittelrhein Immobilien Duelz, i. A. Vonovia SE), info@duelz.de, T 06742 9414875, M 0163 6864447, Objekt-ID 200-039.'::text)),
    '{wunschpreis}', to_jsonb(215000)),
    '{telefon}', to_jsonb('06742 9414875'::text)),
    '{email}', to_jsonb('info@duelz.de'::text)),
    '{updated_at}', to_jsonb(to_char(now() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))),
  updated_at = now()
where data->>'link' = 'https://www.kleinanzeigen.de/s-anzeige/bonn-endenich-kapitalanlage-5-og-mit-3-zkb-mit-balkon-provisionsfrei-/3282873847-196-23694';
